-- StarMKT OS - Esquema inicial
set search_path = public;

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists public.hubs (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  code text not null unique,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text unique,
  role text not null check (role in ('admin','finance','juridico','hub','viewer')),
  default_hub uuid references public.hubs(id),
  is_active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.users_hubs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  hub_id uuid references public.hubs(id) on delete cascade,
  role text not null check (role in ('admin','finance','juridico','hub','viewer')),
  unique (user_id, hub_id)
);

create table if not exists public.providers (
  id uuid primary key default gen_random_uuid(),
  cnpj text not null,
  razao_social text not null,
  email text,
  banco text,
  agencia text,
  conta text,
  hub_id uuid references public.hubs(id),
  is_active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.contracts (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid references public.providers(id) on delete restrict,
  hub_id uuid references public.hubs(id),
  type text not null check (type in ('prestador','cliente')),
  number text,
  start_date date,
  end_date date,
  value numeric(14,2),
  status text not null check (status in ('draft','active','suspended','terminated')) default 'active',
  drive_file_url text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists public.ap_invoices (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid references public.providers(id) on delete restrict,
  hub_id uuid references public.hubs(id),
  contract_id uuid references public.contracts(id),
  nf_number text,
  nf_date date,
  competence date,
  description text,
  amount numeric(14,2) not null,
  status text not null check (status in ('pending','approved','paid','rejected')) default 'pending',
  attachment_url text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  ap_invoice_id uuid references public.ap_invoices(id) on delete cascade,
  paid_at date,
  amount numeric(14,2) not null,
  method text check (method in ('pix','ted','boleto','cartao','outro')),
  proof_url text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists public.reimbursements (
  id uuid primary key default gen_random_uuid(),
  requester uuid references auth.users(id),
  hub_id uuid references public.hubs(id),
  description text,
  amount numeric(14,2) not null,
  expense_date date,
  status text not null check (status in ('pending','approved','paid','rejected')) default 'pending',
  attachment_url text,
  created_at timestamptz default now()
);

create table if not exists public.advances (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid references public.providers(id) on delete restrict,
  hub_id uuid references public.hubs(id),
  amount numeric(14,2) not null,
  request_date date,
  status text not null check (status in ('pending','approved','released','settled','rejected')) default 'pending',
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text not null,
  payload jsonb,
  created_at timestamptz default now()
);

create or replace view public.v_finance_hub_month as
select
  ai.hub_id,
  date_trunc('month', ai.competence) as month,
  sum(case when ai.status in ('approved','paid') then ai.amount else 0 end) as total_despesas,
  sum(coalesce(p.amount,0)) as total_pagamentos
from public.ap_invoices ai
left join public.payments p on p.ap_invoice_id = ai.id
group by 1,2;

alter table public.profiles enable row level security;
alter table public.users_hubs enable row level security;
alter table public.providers enable row level security;
alter table public.contracts enable row level security;
alter table public.ap_invoices enable row level security;
alter table public.payments enable row level security;
alter table public.reimbursements enable row level security;
alter table public.advances enable row level security;

create policy if not exists "profiles_self" on public.profiles
  for select using (auth.uid() = user_id and is_active = true);

create or replace function public.user_in_hub(h uuid)
returns boolean language sql stable as $$
  select exists (
    select 1 from public.users_hubs uh
    where uh.user_id = auth.uid() and uh.hub_id = h
  );
$$;

create policy if not exists "ap_invoices_read" on public.ap_invoices
  for select using (
    exists(
      select 1 from public.profiles pr
      where pr.user_id = auth.uid() and pr.role = 'admin' and pr.is_active
    )
    or user_in_hub(hub_id)
  );

create policy if not exists "ap_invoices_write" on public.ap_invoices
  for insert with check (
    exists(
      select 1 from public.profiles pr
      where pr.user_id = auth.uid() and pr.role in ('admin','finance') and pr.is_active
    )
    and user_in_hub(hub_id)
  );

create policy if not exists "ap_invoices_update" on public.ap_invoices
  for update using (
    exists(
      select 1 from public.profiles pr
      where pr.user_id = auth.uid() and pr.role in ('admin','finance') and pr.is_active
    )
    and user_in_hub(hub_id)
  );

-- TODO: replicar políticas para outras tabelas conforme necessidade

